name: Substring Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  substring:
    runs-on: ubuntu-latest
    steps:
       - name: Extract Substring
         id: extract
         shell: bash
         run: |
           echo "s11=h-j" >> $GITHUB_ENV
       - name: Extract Substring1
         run:  |
          substring_before=$(echo ${{env.s11}} | cut -d'-' -f1)
          echo "s1=${{env.s11}} | cut -d '-' -f 1" >> $GITHUB_ENV
          echo substring_before
     
         

      # - name: use
      #   run: echo "${{env.s1}}"

      # - name: use1
      #   id: get-id
      #   uses: actions/github-script@0.9.0
      #   with:
      #    script: |
      #      const id = ${{env.s1}}.split('-')[1]
      #      echo id

  
      # - name: Extract substring
      #   run: |
      #     original_string="Hello_World"
      #     substring=$(echo $original_string | cut -d'_' -f2-)
      #     echo "The substring after '_' is: $substring"


