name: Substring Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  substring:
    runs-on: ubuntu-latest
    outputs:
      substring: ${{ steps.extract.outputs.s1 }}
    steps:
      - name: Extract Substring
        id: extract
        run: echo "s1=hello" >> $GITHUB_ENV

      - name: use
        run: echo "${{env.s1}}"

