name: Substring Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  substring:
    runs-on: ubuntu-latest
    outputs:
      substring: ${{ steps.extract.outputs.s1 }}
    steps:
      - name: Extract Substring
        id: extract
        shell: bash
        run: $(echo "h-1" | cut -d ' ' -f 2)

      # - name: use
      #   run: echo "${{env.s1}}"

      # - name: use1
      #   id: get-id
      #   uses: actions/github-script@0.9.0
      #   with:
      #    script: |
      #      const id = ${{env.s1}}.split('-')[1]
      #      echo id

  
      # - name: Extract substring
      #   run: |
      #     original_string="Hello_World"
      #     substring=$(echo $original_string | cut -d'_' -f2-)
      #     echo "The substring after '_' is: $substring"


