name: Substring Example

on:
  push:
    branches:
      - main

jobs:
  substring:
    runs-on: ubuntu-latest
    outputs:
      substring: ${{ steps.extract.outputs.s1 }}
    steps:
      - name: Extract Substring
        id: extract
        run: echo "::set-output name=s1::hello"

