name: Substring Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  substring:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Substring
        id: extract
        run: echo "s1=${{"hello-i" | cut -d ' ' -f 1}}" >> $GITHUB_ENV
      # - name: Extract Substring
      #   id: extract
      #   shell: bash
      #   run: |
      #    name="John Doe"
      #    echo ${name} | cut -d ' ' -f 1
         

      # - name: use
      #   run: echo "${{env.s1}}"

      # - name: use1
      #   id: get-id
      #   uses: actions/github-script@0.9.0
      #   with:
      #    script: |
      #      const id = ${{env.s1}}.split('-')[1]
      #      echo id

  
      # - name: Extract substring
      #   run: |
      #     original_string="Hello_World"
      #     substring=$(echo $original_string | cut -d'_' -f2-)
      #     echo "The substring after '_' is: $substring"


