name: Substring Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  substring:
    runs-on: ubuntu-latest
    outputs:
      substring: ${{ steps.extract.outputs.s1 }}
    steps:
      - name: Extract Substring
        id: extract
        run: echo "s1=hello-i" >> $GITHUB_ENV

      - name: use
        run: echo "${{env.s1}}"

      - name: use1
        id: get-id
        uses: actions/github-script@0.9.0
        with:
         script: |
           const id = ${{env.s1}}.split('-')[1]
           echo id

